export type RegionId = "us" | "eu" | "uk" | "global";

export type ThemeMode = "light" | "dark";
export type DepthMode = "plain" | "pro";

export interface Prefs {
  theme: ThemeMode;
  depth: DepthMode;
  lastRegion: RegionId;
}

export interface IndicatorReading {
  id: string;
  label: string;
  value: number | null;
  unit: string;
  source: string;
  asOf: string;
  subScore: number;
  threshold: number;
  weight: number;
  explanation: string;
  formula: string;
  /** True when the latest observation is older than 240 days. The composite
   *  uses 50 (neutral) for stale indicators so the score isn't dragged by
   *  zombie data. The gauge surfaces a "Stale" badge in the header. */
  stale?: boolean;
}

export interface CompositeHistoryPoint {
  date: string;
  score: number;
}

/** A single fact the heuristic picked from the indicators. */
export interface InsightPoint {
  /** Stable kind tag used by the renderer for icon / colour. */
  kind: "concern" | "reassurance" | "notable" | "stale";
  /** Indicator label (or composite reference) */
  label: string;
  /** What the value is, with unit. e.g. "+0.20pp", "53.30", "score 42" */
  value: string;
  /** One-sentence why-it-matters. */
  why: string;
}

export interface RegionInsights {
  /** 60-100 word editorial paragraph. Generated by Groq when key present;
   *  templated fallback otherwise. */
  paragraph: string;
  /** The structured facts the paragraph was built from — surfaced as small
   *  chips below the prose for transparency. */
  points: InsightPoint[];
  /** ISO timestamp of when the insights were drafted. */
  generatedAt: string;
  /** "groq" or "fallback" — used to tag the source in Pro mode. */
  source: "groq" | "fallback";
}

export interface RegionData {
  region: RegionId;
  regionLabel: string;
  score: number;
  band: number;
  generatedAt: string;
  indicators: IndicatorReading[];
  history: CompositeHistoryPoint[];
  recessions: Array<{ start: string; end: string; label?: string }>;
  notes: string[];
  /** Optional: present once the cron has drafted insights. */
  insights?: RegionInsights;
}
